workflows:
  android-debug:
    name: Android Debug
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Build Android debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
