name: Flutter Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # IMPORTANT: Use '3.22.0' exactly
          channel: 'stable'

      - name: Install Android Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: client # IMPORTANT: This tells GitHub to look in your 'client' folder

      - name: Build Android APK
        run: flutter build apk --debug
        working-directory: client # IMPORTANT: This tells GitHub to look in your 'client' folder

      - name: Upload Android Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: client/build/app/outputs/flutter-apk/app-debug.apk # IMPORTANT: This is where your app will be found
